### ISSUE TITLE
Pending PR on bitbucket?

### ISSUE THREAD

**Issue by jjatria** [shlomif/perl-XML-SemanticDiff#6]
[This bug report on RT](https://rt.cpan.org/Public/Bug/Display.html?id=84546) seems to have resulted in [this (partial?) PR](https://bitbucket.org/nicholas_phillips/perl-xml-semanticdiff/commits/a47247aa0cc80bc8d9dec7274d3fc7523d93f332) on BitBucket. However, looking at the project history, it doesn't seem like those changes were merged at all.

Is this still a pending issue? If so, I can put the changes from BitBucket into a Github PR (I'll make sure to keep the commit author the same).

**Comment by shlomif** [comment]
On Thu, 12 Oct 2017 01:10:03 -0700
José Joaquín Atria <notifications@github.com> wrote:

> [This bug report on RT](https://rt.cpan.org/Public/Bug/Display.html?id=84546)
> seems to have resulted in [this (partial?)
> PR](https://bitbucket.org/nicholas_phillips/perl-xml-semanticdiff/commits/a47247aa0cc80bc8d9dec7274d3fc7523d93f332)
> on BitBucket. However, looking at the project history, it doesn't seem like
> those changes were merged at all.
> 
> Is this still a pending issue? If so, I can put the changes from BitBucket
> into a Github PR (I'll make sure to keep the commit author the same).
> 
> 

Please do that. thanks!

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
Selina Mandrake - The Slayer (Buffy parody) - http://shlom.in/selina

I think those “Sent from my $DEVICE” signatures in E-mails are actually bad
publicity for these devices, given the poor quality of most of these E-mails.
    — https://twitter.com/shlomif/status/656868022649561088

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by jjatria** [comment]
Ah! Beaten to it by 195cef35a, it seems. :)

**Comment by shlomif** [comment]
On Thu, 12 Oct 2017 13:21:50 +0000 (UTC)
José Joaquín Atria <notifications@github.com> wrote:

> Ah! Beaten to it by 195cef35a, it seems. :)
> 
> 

I see. Thanks!

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
List of Text Processing Tools - http://shlom.in/text-proc

Whatever women do they must do twice as well as men to be thought of half as
good. Luckily, this is not difficult.
    — https://en.wikiquote.org/wiki/Charlotte_Whitton

Please reply to list if it's a mailing list post - http://shlom.in/reply .
